### ISSUE TITLE
cannot select the draw for delete or update after reload it

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#101]
hi @ivmartel ,
I am integrating the dicom viewer with my project. but the issue is when i draw and save image, it will works fine. and i am trying to load the image again with drawings it is loading but cannot select the drawings for further change. Hope you will guide me with references and solutions. thanks in advance.
What I want is that i wanted to select the retrieved drawings and delete or update it

**Comment by ivmartel** [comment]
Duplicates #102. See progress there.
