### ISSUE TITLE
how to reselect the draw or shape after fetched from database.

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#102]
hai ivmartel,
  This is my second request regarding this questions. I am able to drwa and save the aanotations in the database.and I can retreive the draws and set it in to the viewer. but I cannot select the draws and edit. hope you can help me. any reference will be the great help.Thanks in advance.

**Comment by ivmartel** [comment]
Sorry for answering so late, is this still an issue? Even with the latest version?

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
