### ISSUE TITLE
how to select and edit annotations after db saving

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#104]
i was able to draw and save annoattions  in the database. but i cannot select and edit the drawings after fetched from database.
even i cant able to select the draw. how this problem can be solved?
Thanks in advance

**Comment by ikhizarwork** [comment]
hi @shameerasl  , can you please help me annotations saving in the database and later on retrieving it ? like how you implemented this ?

**Comment by ivmartel** [comment]
You should be able to load a state file via a `app.loadURLs`.

**Comment by ikhizarwork** [comment]
got the following error when trying to load the state from the db :-

Error fetching annotations: TypeError: Cannot read properties of undefined (reading 'split')
    at on.loadURLs (dwv.min.js:1:378291)
    at Vn.loadURLs (dwv.min.js:1:450130)
    at applauncher.js:254:15
    
    here is my code , please let me know if i am doing something wrong over here :-
    
    dbRef.once('value')
    .then(function (snapshot) {
      const annotations = snapshot.val();
      if (annotations) {
   
        const drawings = JSON.parse(annotations);
    
        myapp.loadURLs(drawings);
      }
    })
    .catch(function (error) {
      console.error('Error fetching annotations:', error);
    });

**Comment by ivmartel** [comment]
`app.loadURLs` takes the url of a state file. If you want to process the request as you do in your example, you can pass the JSON string directly to `app.applyJsonState(annotations)`.

**Comment by ikhizarwork** [comment]
I tried the above thing which you have mentioned but still getting the following error :-

Error fetching annotations: TypeError: Cannot read properties of undefined (reading 'getActiveViewLayer')
    at At.apply (dwv.min.js:1:347437)
    at Vn.applyJsonState (dwv.min.js:1:454413)
    at applauncher.js:254:15
    
    and following is my code :-
    
    dbRef.once('value')
    .then(function (snapshot) {
      const annotations = snapshot.val();
      if (annotations) {
        myapp.applyJsonState(annotations);
      }
    })
    .catch(function (error) {
      console.error('Error fetching annotations:', error);
    });
    
    and following is my json file which i am storing in my DB :-
    
    {"version":"0.5","window-center":304,"window-width":608,"position":[128,128,73],"scale":{"x":1,"y":1,"z":1},"offset":{"x":0,"y":0,"z":0},"drawings":{"attrs":{},"className":"Layer","children":[{"attrs":{"name":"position-group","id":"#2-0","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-3","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-4","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-2","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-1","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-5","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-6","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-7","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-8","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-9","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-10","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-11","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-12","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-13","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-14","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-15","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-16","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-17","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-18","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-19","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-20","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-21","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-22","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-23","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-24","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-25","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-26","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-27","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-28","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-29","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-30","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-31","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-32","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-33","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-34","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-35","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-36","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-37","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-38","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-39","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-40","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-41","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-42","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-43","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-44","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-45","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-46","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-47","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-48","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-49","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-50","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-51","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-52","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-53","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-54","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-55","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-56","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-57","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-58","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-59","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-60","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-61","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-62","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-63","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-64","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-65","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-66","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-67","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-68","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-69","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-70","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-71","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-72","visible":false},"className":"Group","children":[]},{"attrs":{"name":"position-group","id":"#2-73"},"className":"Group","children":[{"attrs":{"name":"circle-group","id":"vk1dz3aknir","draggable":true,"x":4.402948402948425,"y":7.547911547911548},"className":"Group","children":[{"attrs":{"x":127.68550368550365,"y":89.94594594594595,"scaleX":1.257985257985258,"scaleY":1.257985257985258,"name":"label"},"className":"Label","children":[{"attrs":{"fontSize":10,"fontFamily":"Verdana","fill":"#ffff80","padding":3,"shadowColor":"#000","shadowOffsetX":0.25,"shadowOffsetY":0.25,"name":"text","text":"3.341 cm²"},"className":"Text"},{"attrs":{"fill":"#ffff80","opacity":0.2,"width":58.939453125,"height":16},"className":"Tag"}]},{"attrs":{"x":127.68550368550365,"y":89.94594594594595,"radius":11,"stroke":"#ffff80","strokeScaleEnabled":false,"name":"shape"},"className":"Circle"},{"attrs":{"x":116.68550368550365,"y":89.94594594594595,"stroke":"#999","fill":"rgba(100,100,100,0.7","strokeScaleEnabled":false,"radiusX":3.773955773955774,"radiusY":3.773955773955774,"name":"anchor","id":"left","dragOnTop":false,"draggable":true},"className":"Ellipse"},{"attrs":{"x":138.68550368550365,"y":89.94594594594595,"stroke":"#999","fill":"rgba(100,100,100,0.7","strokeScaleEnabled":false,"radiusX":3.773955773955774,"radiusY":3.773955773955774,"name":"anchor","id":"right","dragOnTop":false,"draggable":true},"className":"Ellipse"},{"attrs":{"x":127.68550368550365,"y":78.94594594594595,"stroke":"#999","fill":"rgba(100,100,100,0.7","strokeScaleEnabled":false,"radiusX":3.773955773955774,"radiusY":3.773955773955774,"name":"anchor","id":"bottom","dragOnTop":false,"draggable":true},"className":"Ellipse"},{"attrs":{"x":127.68550368550365,"y":100.94594594594595,"stroke":"#999","fill":"rgba(100,100,100,0.7","strokeScaleEnabled":false,"radiusX":3.773955773955774,"radiusY":3.773955773955774,"name":"anchor","id":"top","dragOnTop":false,"draggable":true},"className":"Ellipse"}]}]}]},"drawingsDetails":{"vk1dz3aknir":{"meta":{"textExpr":"{surface}","quantification":{"surface":{"value":3.341010156014926,"unit":"cm²"},"min":{"value":148,"unit":""},"max":{"value":213,"unit":""},"mean":{"value":177.7860962566845,"unit":""},"stdDev":{"value":12.267178035444973,"unit":""}}}}}}

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
