### ISSUE TITLE
Not loading dcm file

### ISSUE THREAD

**Issue by AdolfoBanchio** [ivmartel/dwv-jqmobile#124]
I have a .dcm file, and im trying to view it using the live demo of the dwv-jqmobile version. When i upload the file i see this
![image](https://user-images.githubusercontent.com/78754770/223472752-dbecee75-6af2-434e-83fd-49ffedc52882.png)

Also I would like to know how to integrate the viewer to my website. 
what im doing is downloading the zip from https://github.com/ivmartel/dwv-jqmobile/releases/tag/v0.6.1
pasting it in a folder of my website files, and then using redirecting to the index.html file. And i get the same result

**Comment by ivmartel** [comment]
Could you share the data so that I test on my side?

**Comment by ivmartel** [comment]
This is a multiframe data. If you double click on the image, it will start looping on the frames and you should see non black frames at some point. A single click will then stop the loop. The current 'stable' dwv-jqmobile allows to browse frames with a mouse left button click + horizontal move.
