### ISSUE TITLE
How to load the dicom Zip file faster while using the Url method ? ( i am using input= "url") Method.

### ISSUE THREAD

**Issue by ikhizarwork** [ivmartel/dwv-jqmobile#134]
i have a react application where the user clicks on the Anchor tag to view the dicom image ,  and the anchor tag brings the user to dwv-jqmobile application with the url of that dicom zip file using input="url" method , the problem is since the dicom zip file is quite large , so it is taking longer time to load up and i dont want the end user to wait for such a longer period , so is there any way or method through which i can reduced the waiting period for the end user ? how can the zip file gets loaded much faster using the url method ? 

e.g :- http://127.0.0.1:5500/index.html?input=" URL" 

the zip file gets loaded after a long period of wait, so plz help regarding it .

**Comment by ivmartel** [comment]
It is true the current zip loader waits for all the files to be unzipped before loading the dicoms, it could do it from the first unzipped file. 

But I guess your main bottleneck is the HTTP transfer... And this one cannot be made faster... You could compare to transferring dicom file per dicm file to see if that gives better responsiveness.

**Comment by ikhizarwork** [comment]
can you help me with How to implement the dicom file per dcm file option ?

**Comment by ivmartel** [comment]
Check out the scroll [example](https://ivmartel.github.io/dwv/doc/stable/dwv.tool.Scroll.html#Scroll) and how it uses `app.loadURLs`.

**Comment by ikhizarwork** [comment]
how to execute the scroll example in the canvas Div ? after using the scroll example in index.html file , I'm able to view the dicom images but unable to use other tools , e.g zoomAndpan and so on  ... , the way it use to open using Url input method , i want it to open it that way , inside that canvas div , please let me know how to achieve that ?

**Comment by ivmartel** [comment]
The tools available are the ones you pass to the `app.init`, check out the dwv [demo](https://ivmartel.github.io/dwv/) and the [viewer.js](https://github.com/ivmartel/dwv/blob/develop/tests/pacs/viewer.js) for an example.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
