### ISSUE TITLE
1) can we use AWS S3 bucket to store a folder that contains large files of dicom data ? 2) and then view it using url input method ??

### ISSUE THREAD

**Issue by ikhizarwork** [ivmartel/dwv-jqmobile#137]
After uploading the dicom folder which contains large number of dicom images at AWS S3 bucket , how can we view it in our dwv-jqmobile application ? can we view it using url input method ? and is there any other ways of viewing it as well ? 

p.s - I want to upload the whole folder and not a zip or compressed file, and then view it in our application.

**Comment by ivmartel** [comment]
I have not tried to connect to an AWS bucket yet but I would be interested if anyone did. Providing some integrations for these cloud storage is on my todo list but I do not have much time...

**Comment by ivmartel** [comment]
I hope you found a solution to your problem. If you can share that would be cool.

Closing for now, feel free to comment if you need.
