### ISSUE TITLE
Does this application has 3-axis/3D views? i.e MPR ?

### ISSUE THREAD

**Issue by ikhizarwork** [ivmartel/dwv-jqmobile#138]
Does this has 3-axis/3D views? that is MPR ? saggital view and the other view as well ?

**Comment by ivmartel** [comment]
There is no MPR in this viewer, check out the [dwv-angular](https://github.com/ivmartel/dwv-angular) one that allows to change the view orientation or the dwv [demo](https://ivmartel.github.io/dwv/) that has a full MPR.

**Comment by ikhizarwork** [comment]
is there any update regarding the implementation of MPR for this viewer ?

**Comment by ivmartel** [comment]
Still no MPR here and nothing planned for a near future... Please check the example links of my last comment for example code that you can implement.

**Comment by ikhizarwork** [comment]
MPR was supposed to be implemented in 0.80 milestone ?

**Comment by ivmartel** [comment]
There is no real plan for its integration since I do not have much time these days.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
