### ISSUE TITLE
Unable to view multiple series

### ISSUE THREAD

**Issue by ikhizarwork** [ivmartel/dwv-jqmobile#165]
I am fetching my dicom data from database and trying to display it in the dicom viewer app , but getting error , since its a multiple series of data , there is orientation issue occuring , please help me regarding how to display multiple series dicom data .

**Comment by ikhizarwork** [comment]
getting the following error :-

{error: Error: Cannot append a slice with different number of columns}
{error: Error: Cannot append a slice with different SeriesInstanceUID}

please revert back asap ...

**Comment by ivmartel** [comment]
Relates to #646

**Comment by ivmartel** [comment]
Please follow the linked dwv issue for updates.

Closing for now, feel free to comment if you need.
