### ISSUE TITLE
Unable to Build the app using grunt build command

### ISSUE THREAD

**Issue by ikhizarwork** [ivmartel/dwv-jqmobile#175]
i want to deploy the project on AWS platform and for that i would be needing the build version of this application , and when i am trying to run the build command "grunt build" , it is showing the following error :-

Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.

any help would be highly appreaciated .

**Comment by ikhizarwork** [comment]
i even tried to include the build script inside the gruntfile.js and package.json , still unable to obtain the build folder .

**Comment by ikhizarwork** [comment]
please help with the grunt configuration for building the app for production purpose .

**Comment by ivmartel** [comment]
There is no need to build, the code is ready to run once you install the dependencies (with `--production`). To deploy just copy the folder.

**Comment by ivmartel** [comment]
Hi, sorry for the delay, is this still an issue? 
I fixed a problem with the Google Drive app recently, see #188.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
