### ISSUE TITLE
how to change orientation of images

### ISSUE THREAD

**Issue by noorfatma** [ivmartel/dwv-jqmobile#178]
Hi,

  I am trying to load the images in sagittal view. For that I am changing the orientation of the viewconfig. But i see only a thin line of images. what am I missing. 

```js
const viewConfig0 = new dwv.ViewConfig('layerGroup0');
viewConfig0.orientation = "sagittal";
const viewConfigs = {'*': [viewConfig0]};

// main application
var myapp = new dwv.App();
myapp.init(options);
myapp.setDataViewConfigs(viewConfigs);
```

**Comment by ivmartel** [comment]
If you only load one slice that is axial and try to see it in coronal or sagittal, it is normal that you only see a line. You have to load more than one slice.

**Comment by noorfatma** [comment]
Even when I am loading the folder, the same thing happens. I see a one or two pixel horizontal line. When I scroll, i can see the slices changing in those pixels. I am attaching the screen recording.

https://github.com/ivmartel/dwv-jqmobile/assets/51729029/2c71c743-9ae7-41e5-a4b4-de1215289795

**Comment by ivmartel** [comment]
The library has a default mode to do its first image display when it receives the first image. So at this point, you only have one slice. Reorienting the data results in the line you have.
To create an oriented view after launching a load, you have to wait for all the data to be loaded. Set the app option `viewOnFirstLoadItem` to false and call `app.render(dataId)` when you receive a `load` event.

**Comment by noorfatma** [comment]
Thanks a ton, its working now.
