### ISSUE TITLE
Error on ?input=dicoms_folder.zip

### ISSUE THREAD

**Issue by jpoles1** [ivmartel/dwv-jqmobile#18]
When using the example interface (index.html):
I am trying to load in a zip folder containing a series of DICOM files via a URL parameter. When I navigate to localhost/index.html?input=dicoms_folder.zip I get the error:

`Uncaught (in promise) TypeError: Cannot read property 'name' of undefined at dwv.js:18564`

The line in question appears to be: 

` filename = zobjs[num].name;`

**Comment by ivmartel** [comment]
It is working for me. Are you sure of your zip file? I get the same error when the zip file does not contain data.

**Comment by ivmartel** [comment]
I hope you managed to make it work. Closing for now, feel free to comment if you need.

**Comment by DICOMSOFT** [comment]
i've same problem. I solved it in adding extension file ".dcm" to dicom file.

**Comment by ivmartel** [comment]
IO readers are chosen according to the file/url extension, see their `canLoadFile` or `canLoadUrl` methods. The dicom one handles files with no extension or the 'dcm' extension.
