### ISSUE TITLE
how to integrate with new orthanc versions ..?

### ISSUE THREAD

**Issue by mmohalil** [ivmartel/dwv-jqmobile#186]
I like your greate project and i think it is the most mobile compatable opensource HTML viewer , i can load local files as well as remote files but one after one in the URL .
what i seeking for is to integrate it with ORTHANC dicom server new versions ( Iam woring on  1.12.3) to load complete series . 
any ideas or tutorial ..?
thanks

**Comment by ivmartel** [comment]
I did an Orthanc plugin some time ago: https://github.com/ivmartel/dwv-orthanc-plugin
It needs updating!

**Comment by mmohalil** [comment]
thanks for your replay , 
but please any more explanation ,
what is the URL for using the dicomweb  method .
i noticed that the stone viewer for example use some thin like with orthanc in the backgound 
http://192.168.1.128:8042/stone-webviewer/index.html?study=1.2.840.113619.2.81.325.1.24608.20220324.311815

how i can achive same thing like that with DWV- jqmobile
i tried 
http://192.168.1.128/index.html?study=1.2.840.113619.2.81.325.1.24608.20220324.311815
 but with no luck 
thanks for help

**Comment by ivmartel** [comment]
Going the dicom web way will need more development since you will need to deploy a custom dwv-jqmobile that can connect to Orthanc, it's maybe easier to go the plugin way. I'll see if I can find time to update the plugin.

**Comment by ivmartel** [comment]
Ok, I had a look at the plugin and it is quite out-dated... 

@mmohalil did you make some progress?

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
