### ISSUE TITLE
how to save annotations in database and retrieve it later on from database (jq-mobile) ?

### ISSUE THREAD

**Issue by ikhizarwork** [ivmartel/dwv-jqmobile#189]
i want to store the annotations made by me in the database rather than saving it locally , and similarly want to retrieve it later on with the loading of the dicom file .

**Comment by ikhizarwork** [comment]
i am able to save the annotations to my database , now just need help on how to retrive that json state with the dicom file .

**Comment by ivmartel** [comment]
Duplicates #104, see answers there.

**Comment by ivmartel** [comment]
Answered in #104.
