### ISSUE TITLE
Can we use this application on On-premises ? over intranet ?

### ISSUE THREAD

**Issue by ikhizarwork** [ivmartel/dwv-jqmobile#197]
I just wanted to know whether can we use this app on onpremises setup ? where intranet is use ?
if Yes , then what are the changes we will have to make in this app ?

**Comment by ivmartel** [comment]
You can use this code on an intranet yes, no changes should be needed.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
