### ISSUE TITLE
How to load local dcm files by default

### ISSUE THREAD

**Issue by xixihappy** [ivmartel/dwv-jqmobile#25]
I used this.dwvApp.loadURLs () to load init dwv in applauncher.js and nothing happens

**Comment by ivmartel** [comment]
Check out this fiddle: [DWV display example #1](https://jsfiddle.net/ivmartel/LteeL0gf/) for an example usage of `loadURLs`.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
