### ISSUE TITLE
Unable to select folder from mobile app

### ISSUE THREAD

**Issue by Nagaraj8088** [ivmartel/dwv-jqmobile#27]
We are trying to integrate` dwv-jqmobile v0.3.0/v0.2.0` to the mobile app using web view, web app runs fine but finds few bugs.

- Unable to select the local directory/folder, selecting only files.
- Getting error while choosing Google Drive, unable to connect.

**Comment by ivmartel** [comment]
Sorry for the late answer...
- the folder loading depends on the browser, but should be supported on the main browsers
- dwv-jqmobile uses a local version of the Google API that gets out of date sometimes, I need to find a solution for this...

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.

**Comment by ivmartel** [comment]
For the google drive error, please follow #32.
