### ISSUE TITLE
iframe integration

### ISSUE THREAD

**Issue by smartydoctor** [ivmartel/dwv-jqmobile#28]
Good day,
Please, I need to integrate iframe tag to my WP site and initiate local links from my website including jpg/dcm! I don't know much code.
if there anyway else to integrate the viewer framework + (my local links) I would  be grateful for help.
Thanks.

**Comment by ivmartel** [comment]
Check out the dwv wordpress plugin: [dicom-support](https://wordpress.org/plugins/dicom-support/).

**Comment by smartydoctor** [comment]
Thanks for your reply,
I need to add the tool support for the images including (scroll, zoom/pan and window level only).
I think those features are not there in that WP plugin (it is just for converting DCM to jpg), correct me if I wrong :)

**Comment by ivmartel** [comment]
The WP plugin does provide the functionalities you list (scroll, zoom/pan and window level). I'm working on re-creating a demo page since the current one went down...

**Comment by ivmartel** [comment]
Here is the new demo url of the [wordpress plugin](https://tyarcaouen.synology.me/wordpress/). The scroll option is only available for multi slice data.

**Comment by ivmartel** [comment]
_(I updated to the demo link in my previous comment)_

**Comment by smartydoctor** [comment]
I'm sorry for disturbing you again. what is the short code for wordpress multislice images? 
please, give an example with short code.
thanks again

**Comment by ivmartel** [comment]
@smartydoctor, see [dwvblog/multiple-slices](https://tyarcaouen.synology.me/wordpress/dwvblog/multiple-slices/) for some info.
In the future, it would be best to ask questions on the plugin wordpress [page](https://wordpress.org/support/plugin/dicom-support/), thanks!

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
