### ISSUE TITLE
Error in loading different file types(eg. jpeg, png) than DCIM through loadURLs

### ISSUE THREAD

**Issue by namanguptaten** [ivmartel/dwv-jqmobile#37]
I have created a url using blob as we have bytearray and passing that url to **loadURLs** function but that is unable to load that file

**Comment by ivmartel** [comment]
I answered on [dwv/issues/777](https://github.com/ivmartel/dwv/issues/777).

**Comment by ivmartel** [comment]
The underlying issue [dwv/issues/739](https://github.com/ivmartel/dwv/issues/739) is fixed. Closing for now, feel free to comment if you need.
