### ISSUE TITLE
how to view multiple dcm file 

### ISSUE THREAD

**Issue by ahmedelkashef** [ivmartel/dwv-jqmobile#39]
Hi 
i want to display multiple dcm file using url , actually i used to display one file by using this url : https://ivmartel.github.io/dwv-jqmobile/demo/stable/index.html?input={fileUrl} 

i'm wondering if there is a way to do the same with multiple dcm files ?

Thanks

**Comment by ivmartel** [comment]
Yes, check out the dwv wiki [User-Stories#dwv-urs-io-005-data-url-scheme](https://github.com/ivmartel/dwv/wiki/User-Stories#dwv-urs-io-005-data-url-scheme).

For example: `https://ivmartel.github.io/dwv-jqmobile/demo/stable/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void`

(decoded: `https://ivmartel.github.io/dwv-jqmobile/demo/stable/index.html?input=https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/?file=bbmri-53323851.dcm&file=bbmri-53323707.dcm&file=bbmri-53323563.dcm&file=bbmri-53323419.dcm&file=bbmri-53323275.dcm&file=bbmri-53323131.dcm&dwvReplaceMode=void`)

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment.
