### ISSUE TITLE
Can I run it on Windows 7 32-bit computer

### ISSUE THREAD

**Issue by LingZ12** [ivmartel/dwv-jqmobile#49]
19/5000 
Can I run it on Windows 7 32-bit computer

**Comment by ivmartel** [comment]
Good question! Theoretically yes but I cannot test so can't confirm, do you have access to such machines? As long as there is a quite recent browser it should be ok.

**Comment by LingZ12** [comment]
This problem occurs on 32 bits when I load a set DICOM  
![1608193965(1)](https://user-images.githubusercontent.com/36194330/102463221-caab8b00-4085-11eb-9c40-31500559d341.png)

**Comment by LingZ12** [comment]
This problem occurs on 32 bits when I load a set DICOM
![1608193965(1)](https://user-images.githubusercontent.com/36194330/102463302-e747c300-4085-11eb-85cd-b278543afda2.png)

**Comment by ivmartel** [comment]
Which browser are you using? And what version?

**Comment by LingZ12** [comment]
chrome 32bit 87.0.4280.88

**Comment by LingZ12** [comment]
May I ask if this error is related to 32 bits or the code needs to be modified

**Comment by ivmartel** [comment]
The code does not specifically ask for 64/32bits. I'm not sure if the error is related to 32bits or maybe the data is too big for the memory you have. Can you share details about what you are trying to load?

**Comment by LingZ12** [comment]
19/5000 
Could you please provide the email address? The file is too big to upload

**Comment by ivmartel** [comment]
My email is in my github profile.

**Comment by LingZ12** [comment]
Can DICOM images be set in ascending or descending order

**Comment by ivmartel** [comment]
There is no setting for the slice order, dwv uses the image position patient field to sort data.

**Comment by ivmartel** [comment]
Did you make any progress on this issue? Your data loads ok on a 64bits machine.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.

**Comment by LingZ12** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by ivmartel** [comment]
Translation: "This is a holiday automatic reply email from QQ mailbox. Hello, I am currently on vacation and cannot reply to your email in person. I will get back to you as soon as possible after the holiday."
Ok!
