### ISSUE TITLE
Load over ?input= does not work on Firefox

### ISSUE THREAD

**Issue by DominikMa** [ivmartel/dwv-jqmobile#54]
For me loading DICOM files over the `?input` URL parameter does not work in Firefox but does work fine in Chrome.

In https://github.com/ivmartel/dwv-jqmobile/blob/0cd6614dd07e4d55353f3ff700fc71b39ec35bd8/src/applauncher.js#L127 Firefox throws the error `Uncaught TypeError: event is undefined`.
According to https://developer.mozilla.org/en-US/docs/Web/API/Window/event and https://stackoverflow.com/questions/9636400/event-equivalent-in-firefox Firefox does not always have the global `event` property.

Loading the file over URL through the menu works fine too. In this case the `event` is defined. Same for loading from file.

**Comment by ivmartel** [comment]
I think it is more an error on my side, the input `event` var is commented when it should not... Thanks for reporting!

**Comment by ivmartel** [comment]
Looking better now! see [brainmri](https://ivmartel.github.io/dwv-jqmobile/demo/trunk/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void) demo (if already visited, you need to unregister the service worker to really refresh the code).

**Comment by DominikMa** [comment]
Works fine, thank you!
