### ISSUE TITLE
Launching issue..

### ISSUE THREAD

**Issue by anoob09** [ivmartel/dwv-jqmobile#7]
When I launch the index.html page. I see a screen telling me to authorize with Google Drive. But nothing is responsive on the page and I can't do anything.

**Comment by ivmartel** [comment]
It seems you just opened the html in a browser. To see it work, you need to serve it either with a server of your own or by launching `npm run start` or `yarn run start` from a terminal in the dwv-jqmobile folder. Be aware that you need to install all the dependencies first with a `npm install` or `yarn install` all.

**Comment by anoob09** [comment]
I am using Apache. Will that work? And when I launched demo through the browser it worked fine. I don't understand what's the problem here

**Comment by ivmartel** [comment]
Any server will do. Could you explain what did work and what did not?

**Comment by anoob09** [comment]
https://ivmartel.github.io/dwv-jqui/
This link contains the Demo for dwv-mobile. So when I launch dwv-mobile through this. It works fine. But I can't launch it through the zip file I downloaded.

**Comment by anoob09** [comment]
I am getting following error when I running the command in cmd
```C:\Users\anoob\Downloads\dwv-jqmobile-master>yarn install
'yarn' is not recognized as an internal or external command,
operable program or batch file.```

**Comment by ivmartel** [comment]
Ok, nice to know the demo works fine!

If you want to run from source, you need a package manager: [npm](https://www.npmjs.com/get-npm) or [yarn](https://yarnpkg.com). You then can launch `yarn install` to install dependencies and then `yarn run start` to start a local server with the viewer (replace `yarn` with `npm` if you installed `npm`).

**Comment by ivmartel** [comment]
It seems you do not have access to the url, maybe try again. If not, it could be that it is blocked by a firewall on your side.

You need `yarn` or `npm` to install dependencies. Once done, you can serve the dwv folder from your Apache.

**Comment by ivmartel** [comment]
I hope your issue is solved. Closing for now. Feel free to comment / reopen if you need.
