### ISSUE TITLE
Can i set value input from database? Or image dicom from database 

### ISSUE THREAD

**Issue by 1hilari** [ivmartel/dwv-jqmobile#77]

**Comment by ivmartel** [comment]
Not directly via queries, only via urls.

**Comment by 1hilari** [comment]
can i autofill url input?

**Comment by ivmartel** [comment]
I do not know your use case. 
If you are using dwv-jqmobile directly, you can pass urls on the 'main' url as explained [there](https://ivmartel.github.io/dwv/doc/stable/tutorial-user-stories.html#dwv-urs-io-005-data-url-scheme). This how the demo works, for example [bbmri](https://ivmartel.github.io/dwv-jqmobile/demo/stable/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void).
If you are building an app on top of dwv, you can pass urls via the `app.loadURLs`.
