### ISSUE TITLE
How to load DICOMDIR with more than one image series

### ISSUE THREAD

**Issue by billyk18278** [ivmartel/dwv-jqmobile#79]
Thank you very much for DWV i have been using it in research projects for quite a time.

I am using it mainly to serve server-side stored DICOM in a subfolder e.g., data. 
I have two issues.

a) I try to open DICOMDIR  by dwv-jqmobile/?input=data/DICOMDIR

This works only for DICOMDIRs referring to a single image series, if more that one is present then only one is shown.
Is there a way to workaround this?

b)Scroll works in DWV-jqmobile 0.26.0 but does not in dwv-jqmobile 0.7.0-beta
I have tried with various DICOMDIRs, this issue is not significant since i can do my work with 0.26

**Comment by ivmartel** [comment]
a. dwv-jqmobile and the underlying dwv expect just one image series, it is left to the user to sort series
b. this [trunk demo](https://ivmartel.github.io/dwv-jqmobile/demo/trunk/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void) works fine and the data can be scrolled, could the problem be the DICOMDIR?

**Comment by billyk18278** [comment]
Thank you for your fast response.
a) ok, I assume what i can do is avoid using a DICOMDIR with various series and open several browser tabs pointing DWV to each seperate subfolder's files after zipping them to one zip per folder. right?

b)After searching more, the problem is for sure related with DICOMDIRs referring to more than one series. 
The weird thing is that in 0.26 scroll works. Of course scroll works normally in a zip without DICOMDIR.

If you want i can share my tests

**Comment by ivmartel** [comment]
Follow [dwv #646](https://github.com/ivmartel/dwv/issues/646) for a series filter, not sure how it will look like...
If you can, please share your tests, I do not have that much DICOMDIRs.

**Comment by billyk18278** [comment]
> Regarding solution a) I saw that If i ommit DICOMDIR then i must add .dcm suffix to each file in each series folder before zipping in order for the zip to be identified, is there another way that you can think of?

I have done this but it does not solve the problem i get "Error: Cannot append a slice with different number of columns" and again only one series is loaded... I guess the DICOMDIR includes several series that might be of different resolution.

Is it possible to ignore the problem and display the images?

**Comment by ivmartel** [comment]
I hope you managed to solve your problem, sorry for not answering earlier...
Closing for now, feel free to comment if you need.
