### ISSUE TITLE
DWV mobile + DWV Support (WordPress plugin)?

### ISSUE THREAD

**Issue by adammesa** [ivmartel/dwv-jqmobile#81]
Hello,

I'm wondering if there are any plans to allow the DWV support wordpress plugin to integrate DWV mobile (or alternatively, for DWV support to be uploaded to Github so that others may contribute/fork it). Currently really appreciate the plugin but would love are more modern UI like the one used by DWV-jqmobile or something like a slider to change window level and slice. 

https://user-images.githubusercontent.com/2158302/165861878-2e7c8ec7-bd51-4981-95ea-1fa950e90cdb.mp4

**Comment by ivmartel** [comment]
Hi, I'm looking for ways to link the wordpress svn with a git repo, if you know of a good solution, I'll implement it.
Regarding functionalities, I do not have much time, all help is appreciated!

**Comment by ivmartel** [comment]
Some pointers: https://cic.ubc.ca/ and their repos: https://github.com/UBC-CIC
