### ISSUE TITLE
not loading dwv-jqui in javascript html project

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#83]
hai,
 i am new to ivmartel and dwv. i need to integrate dwv-jqui in my project which contains html and javascript only. but i have noticed that  dwv-jqui contains node libraries(node modules).when i normally integrate this with script tag and try to load inside my webpage, it is not working properly.do you have any resolution regarding this.

**Comment by ivmartel** [comment]
The release zips should contain all the needed code to run the viewer. You can find them at: https://github.com/ivmartel/dwv-jqmobile/releases
