### ISSUE TITLE
can a image open in dicom web viewer(dwv-jqmobile) from a html5 page.

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#85]
hai,  I have an issue when I tried to open an image from my page (html) with a button click in dwv-jqmobile viewer by giving the path url , it will not open the image. but it is working when I click tool box in the dwv viewer, it will open the file which i chose.
but i want to open an image with button click in dicom web viewer.i hope you may help me to get the knowledge.....and thanks in advance....

**Comment by ivmartel** [comment]
There is probably something wrong with the url you pass to the viewer. If you can share it, I can have a look. And what does the browser console say?

**Comment by shameerasl** [comment]
var dicom = 'http://10.176.15.35:8080/dwvimg/P552200009.dcm';
var url = 'http://10.176.15.35:8080/DCTCDev/ivmartel/index.html'+'?input='+dicom;
window.open(url,"_blank","scrollbars=yes,resizable=yes,width=600,height=70");
![image](https://user-images.githubusercontent.com/102153752/171612982-3306e34d-a6dc-4d5a-b64d-a21f7c556009.png)

**Comment by ivmartel** [comment]
You have a 404 error on the dicom data link so the viewer cannot show it.

**Comment by shameerasl** [comment]
hai @ivmartel ,
 Thank you for your response. i have cleared it.and it is working now.
I have one more issue , that how to open a folder dynamically in the viewer

**Comment by ivmartel** [comment]
You can open a folder via `+`and select 'Folder'. Via url, you can pass a list of files or a DICOMDIR, not a folder.

**Comment by shameerasl** [comment]
@ivmartel 
do you have any example code? i am a newbie , so any example code will help me to solve this.
Thankyou

**Comment by shameerasl** [comment]
@ivmartel  ,
and one more is i want to open folder dynamically from another page  not from viewer page.
 I think that  the answer you shared is open from the viewer. please help me to open multiple images from folder  using a button click.

**Comment by ivmartel** [comment]
Ok, closing since this issue is fixed, regarding folders, see #86
