### ISSUE TITLE
dynamically open multiple images from folder in dicom web viewer

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#86]
how to open multiple  dicom images from a folder dynamically into the dicom web viewer?
I can open one image dynamically by passing url. but how do I open a folder and display all images in viewer dynamically.

**Comment by ivmartel** [comment]
Here is a multiple file example: https://jsfiddle.net/ivmartel/hmetaz6f/ (more examples at [tutorial-examples](https://ivmartel.github.io/dwv/doc/stable/tutorial-examples.html)).

**Comment by shameerasl** [comment]
can i use the above example in dwv-jq mobile viewer.
i have used the  code in  ivnartel/dwv-jq mobile index.html .but it is not working . 



var app = new dwv.App();
app.init({
  dataViewConfigs: {'*': [{divId: 'layerGroup0'}]},
  tools: {
    Scroll: {}
  }
});

app.addEventListener('load', function () {
 // alert("inside");
  app.setTool('Scroll');
});

app.loadURLs(['http://localhost:8080/DCTCDev/scripts/dwvimg/6.dcm','http://localhost:8080/DCTCDev/scripts/dwvimg/7.dcm','http://localhost:8080/DCTCDev/scripts/dwvimg/8.dcm']);

hope you can help me to load the files from a folder.

**Comment by ivmartel** [comment]
What error do you get?

**Comment by shameerasl** [comment]
it doesnot show any error , it loads only one image in the viewer. and scroll is not working.

**Comment by shameerasl** [comment]
![image](https://user-images.githubusercontent.com/102153752/174769903-d145b07c-8e79-4e61-9696-4381631bd4d8.png)
[](url)

I have also given as array in input url and it shows the above alert
var farray=[];
farray.push('http://localhost:8080/DCTCDev/scripts/dwvimg/'+patient.pat_reg_id+'/6.dcm');
farray.push('http://localhost:8080/DCTCDev/scripts/dwvimg/'+patient.pat_reg_id+'/7.dcm');
var url = 'http://localhost:8080/DCTCDev/scripts/ivmartel/index.html'+'?input='+farray;
window.open(url);


and also following error in console
![image](https://user-images.githubusercontent.com/102153752/174770551-1439ad83-5892-4178-9ccc-ba030e1b8669.png)


and in my script part i gave the following code


var app = new dwv.App();
app.init({
  dataViewConfigs: {'*': [{divId: 'layerGroup0'}]},
  tools: {
    Scroll: {}
  }
});

app.addEventListener('load', function () {

  app.setTool('Scroll');
});

**Comment by ivmartel** [comment]
Sorry for now answering earlier... Difficult to tell from your snapshot, you would have to expand the error to get more details.
Closing for now, feel free to comment if you need.
