### ISSUE TITLE
how to upload multiple images in the dwv-jqmobile viewer dynamically

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#88]
i am facing the issue that it will not loading multiple images by passing multiple url in an array. it just upload one image and not showing others. when scroll button clicked it is not working.

**Comment by shameerasl** [comment]
![image](https://user-images.githubusercontent.com/102153752/176363330-bb59f403-2264-4e6f-8152-960e07bde72a.png)

![image](https://user-images.githubusercontent.com/102153752/176363446-f2a65d9c-40f2-4694-93a3-97008dedd153.png)
 these are the iissues shown in console

**Comment by ivmartel** [comment]
Are your urls correct? A 403 error is an access error, maybe the code cannot access them.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
