### ISSUE TITLE
how to controll scroll event in multiple image load

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#90]
hai,
   i am using dwv-jqmobile for a while. and it is quite nice. how to access the control of Scroll event. 
in which function from which js is calling scroll function.
 , i have multiple images to load . and after loading these images using app.loadURL i also wanted to call a database function for each images.
that is i want to fetch some information of currently loaded image from database using scroll event.

**Comment by ivmartel** [comment]
Hi! Check out this dwv demo: https://jsfiddle.net/ivmartel/zvt0xemc/, it uses the `slicechange` event (dwv v0.30). In the next version (v0.31) this event will change to be called `positionchange`.
When all the data is loaded, the app sends a `load` event.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
