### ISSUE TITLE
issues regarding toolbox

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#91]
1)tool box annotations are not working in dwv-jqmobile.but add button (+) is working . others are not working.what js and function is controll this event . could you please help me to solve this.

2)i found that you are using "dwv-0.29.1.min.js" in DWV image display example with multiple slices and its own tool (https://jsfiddle.net/ivmartel/jb7fe6yx/). but in dwv-jqmobile we are using "dwv.min.js".when i integrated the https://jsfiddle.net/ivmartel/jb7fe6yx/ code in my dwv-jqmobile code my tool box is not showing. how can i resolve this. hope u will consider my issues and help.. any references will be the great help[ for me. because i am a newbie in dicom web viewer.Thanks in advance.

**Comment by ivmartel** [comment]
1) which version are you trying? this [example](https://ivmartel.github.io/dwv-jqmobile/demo/trunk/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void) seems to be working fine

2) the official release that comes with npm will provide a `dwv.min.js`. For the examples, I use versions that are stored on github and that go by `dwv-X.Y.Z.min.js`. Please use the official npm release.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
