### ISSUE TITLE
Toollist box is not working for dynamically loaded images in dwv-jq-mobile.

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#92]
```js
var dicom_files = [
    ['http://localhost:8080/DCTCDev/scripts/dwvimg/'+obj.pat_reg_id+'/P552200009.dcm'],
    ['http://localhost:8080/DCTCDev/scripts/dwvimg/'+obj.pat_reg_id+'/test.dcm']
];
var app = new dwv.App();
app.init({
    dataViewConfigs: {'*': [{divId: 'layerGroup0'}]},
});
app.loadURLs(dicom_files[0]);
var actions = document.getElementById('actions');
var table=document.createElement('table');
var tr = document.createElement('tr');  
for (var i = 0; i < dicom_files.length; i++) {
    var td = document.createElement('td');
    var new_button = document.createElement('button');
    new_button.setAttribute('data-file-index', i);
    new_button.textContent = 'DICOM Files ' + (i + 1);
    new_button. style. width = '120px';
    new_button.addEventListener('click', dicom_files_selected);
    td.appendChild(new_button);
    tr.appendChild(td);
    table.appendChild(tr)
    actions.appendChild(table);
}
function dicom_files_selected(event) {
    event.preventDefault();
    var button = this;
    var selected_index = parseInt(button.getAttribute('data-file-index'));
    app.abortLoad();
    app.loadURLs(dicom_files[selected_index]);
    dwvjq.gui.Loadbox();
    dwvjq.gui.UrlLoad();
    dwvjq.gui.Toolbox();
    dwvjq.gui.Draw ();
```

in my above code the tool list box is not working.(it is not showing). To give annotations i want to click the tool list box. I am loading images dynamically using url  and with button click i able to change the images as I want.. any reference will be the great help.Thanks in advance

**Comment by ivmartel** [comment]
Hi, the core library (dwv) does not provide a GUI like the toolbox, the GUI is provided by the client code like the one of this repository (dwv-jqmobile). See [src/gui/tools.js#L9](https://github.com/ivmartel/dwv-jqmobile/blob/master/src/gui/tools.js#L9) for some demo code.

**Comment by shameerasl** [comment]
@ivmartel ..Thank you for your response. I got it. I have a clarification, when I load the multiple images , the image color is varying. why this happens in my viewer.

**Comment by shameerasl** [comment]
how to set that colourMap property.. 
could you have any example code

**Comment by ivmartel** [comment]
I answered in #94. If this issue is resolved, can you close it please?

**Comment by shameerasl** [comment]
Thanks @ivmartel
