### ISSUE TITLE
image color change on loading in dwv-jqmobile viewer

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#94]
Hai @ivmartel 
when I am loading images dynamically, its color is changing. i am loading the files from a button click. so how to resolve this issue. Please give a guidance...
Thanks in advance...

**Comment by ivmartel** [comment]
By default, overlay data comes with the rainbow colour-map, you can set it in the data view config under the colourMap property.

**Comment by shameerasl** [comment]
how to set that colourMap property..
could you have any example code
is it given inside the following format
var app = new dwv.App();
app.init({
    dataViewConfigs: {'*': [{divId: 'layerGroup0'}]},
    colourMap:""  //dont know how to set the property here

});

**Comment by ivmartel** [comment]
You have to pass it a valid lut object as defined in the `src/image/lut.js`. It is a per data setting so that you can set different ones.
```js
dataViewConfigs : {
  '*': [
    {
      divId: 'layerGroup0', 
      colourMap: dwv.image.lut.hot_iron
    }
  ]
}
```

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
