### ISSUE TITLE
image draw overlaying issues

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv-jqmobile#96]
In multiple image loading , I loaded  the first image and added drawings. and in a button click or scroll second image will display, but also the first image drawing are visible . this is may be due to the overlaying of images .how to resolve this.

**Comment by ivmartel** [comment]
Hi, what version of the viewer are you using? I tried reproducing with the online demo but it is working for me.

**Comment by shameerasl** [comment]
hi,

  "name": "dwv-jqmobile",
  "version": "0.7.0-beta", this is my viewer version.

![image](https://user-images.githubusercontent.com/102153752/182127808-06815671-8af1-455b-a25d-ec72cb5ddca2.png)

  
and the above figure  is my problem . there multiple image buttons. each when i click the button it will overlap with the previous image.(I dont know whether it is overlapping or not.)could you help me to resolve this

**Comment by ivmartel** [comment]
ok, you seem to be loading new data in an existing instance of the app, are you? The app class does provide a `reset` that you can call before loading the next data.

**Comment by shameerasl** [comment]
![image](https://user-images.githubusercontent.com/102153752/182131205-f1f55a3c-ef28-4b9f-a536-5c0456903749.png)

![image](https://user-images.githubusercontent.com/102153752/182131313-2a5d1f46-c326-4085-ad26-b77270c734ce.png)


these are the error showing when i execute the following code

 myapp.reset();
    myapp.loadURLs([image_url],[{name:"contentType", value:"image/jpeg"}]);

**Comment by shameerasl** [comment]
how to give reset function in applauncher.js? where to give this command for resolving the issue ?
please comment , any references will be  graet help.

**Comment by ivmartel** [comment]
Sorry for now answering earlier, I hope you solved your problem.
Closing for now, feel free to comment if you need.
